backend:
  name: gitlab
  repo: 22silverbullets/
  auth_type: pkce # Required for pkce
  app_id:  # https://gitlab.com/groups/22SilverBullets/-/settings/applications
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    folder: "content/posts/"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown"}